#spring.application.name=piche-banking

spring:
  application:
    name: piche-banking
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:piche_bank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:h2:mem:piche_bank
    user: sa
    password: ''
    driver-class-name: org.h2.Driver
    locations: classpath:/db/migration
  h2:
    console:
      enabled: true
